Repository lactofreee/Plaist, pull requests merged in 2024-12, with the labels that each got.

#9 [merge / 8-feature-jwt-토큰을-이용한-사용자-인증-기능-구현] ✨ feat: README.md 파일 내용 수정
  README.md
Labels: enhancement

#10 [merge / 5-feature-mock-api-테스트-코드-작성-1 ] ✅ test: 가상 검색 기능 api 구현
  src/App.tsx
  src/api/api.ts
  src/layouts/RootLayout.tsx
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/handlers/SearchHandlers.ts
  src/mocks/handlers/browser.ts
  src/mocks/handlers/handlers.ts
  src/mocks/handlers/personalizationHandler.ts
  src/mocks/handlers/searchHandler.ts
  src/mocks/personalizationHandler.ts
  src/mocks/searchHandler.ts
  src/pages/Category.tsx
  src/pages/Main.tsx
  src/pages/test/SearchTest.tsx
Labels: enhancement

#34 [merge / 20-feature-main-feed-퍼블리싱] 🐛 fix: 레이아웃 깨지는 현상 일부 수정
  src/App.tsx
  src/components/Root/Nav.tsx
  src/components/main/MainAllCourse.tsx
  src/components/main/MainBestCourse.tsx
  src/components/main/MainTitle.tsx
  src/components/main/TestCard.tsx
  src/layouts/BlurGlassLayout.tsx
  src/layouts/MainLayout.tsx
  src/layouts/NoBlurLayout.tsx
  src/layouts/RootLayout.tsx
  src/pages/Login.tsx
  src/pages/Main.tsx
  tailwind.config.js
  vite.config.ts
Labels: bug

#45 [merge / 20-feature-main-feed-퍼블리싱] 🐛 fix: 20241211 작업 내용 병합 및 충돌 수정
  src/App.tsx
  src/assets/images/course_img.svg
  src/assets/images/like_filled_icon.svg
  src/assets/images/like_icon.svg
  src/assets/images/location_icon.svg
  src/assets/images/search_icon.svg
  src/components/main/MainAllCourse.tsx
  src/components/main/MainBestCourse.tsx
  src/components/main/MainTitle.tsx
  src/components/main/TestCard.tsx
  src/components/main/allCourse/AllCourseCards.tsx
  src/components/main/allCourse/AllCourseHeader.tsx
  src/components/main/allCourse/AllCourseSortToggle.tsx
  src/components/main/allCourse/SearchInputFeild.tsx
  src/components/main/bestCourse/BestCourseCardItem.tsx
  src/components/main/bestCourse/BestCourseCards.tsx
  src/layouts/MainLayout.tsx
  src/layouts/RootLayout.tsx
  src/pages/Main.tsx
  src/utils/importImages.ts
  tailwind.config.js
Labels: bug

#73 [merge / 51-feature-메인-피드-게시물-노출-기능-구현] 📝 add: .env, .ginignore 파일 수정
  .env
  .gitignore
  src/App.tsx
  src/assets/images/importImages.ts
  src/assets/images/like_not_filled_border_icon.svg
  src/components/main/allCourse/AllCourseCardItem.tsx
  src/components/main/allCourse/AllCourseCards.tsx
  src/components/main/bestCourse/BestCourseCardItem.tsx
  src/components/main/bestCourse/BestCourseCards.tsx
  src/components/main/courseContent/CourseContentDoc.tsx
  src/layouts/CourseContentLayout.tsx
  src/layouts/MainLayout.tsx
  src/pages/CourseContent.tsx
  src/pages/Main.tsx
  src/pages/MainFeed.tsx
  src/types/mainfeed/props.d.ts
Labels: documentation

#83 72 feature 로그인 과 회원가입 유효성 검사, 로그인 유무에 따른 알림 버튼의 페이지 이동 구현
  src/App.tsx
  src/components/InputField.tsx
  src/components/Root/HeaderIcon.tsx
  src/components/Root/Nav.tsx
  src/hooks/useCookie.ts
  src/pages/Login.tsx
  src/pages/Signup.tsx
Labels: enhancement

#91 [merge / 68-feature-코스생성-flow3-퍼블리싱 ]✨ feat: flow3 퍼블리싱
  src/assets/images/course/course_selected_img.svg
  src/assets/images/importImages.ts
  src/pages/createcourse/ExpainCourse.tsx
Labels: enhancement

#92 ✨ Feature: category 기능 구현 완료, postAPI, post Store, channelStore 생성 및 파일 수정
  src/App.tsx
  src/api/api.ts
  src/api/axios.ts
  src/api/channelApi.ts
  src/api/postApi.ts
  src/components/category/Feed.tsx
  src/components/category/Menu.tsx
  src/components/main/allCourse/AllCourseCardItem.tsx
  src/components/viewMycourse/MyCourseSearch.tsx
  src/css/category.css
  src/pages/CreateChannel.tsx
  src/pages/createcourse/SelectStyle.tsx
  src/pages/createcourse/SelectTag.tsx
  src/pages/createcourse/ViewMycourse.tsx
  src/stores/channelStore.ts
  src/stores/postStore.ts
  src/stores/viewMyCourseStore.ts
  src/types/channel.d.ts
  src/types/post.d.ts
Labels: documentation

#95 [merge / 94-feature-코스생성탭에서-하단탭-사용x ]✨ feat: 코스생성탭에서 하단탭사용X
  src/components/Root/Nav.tsx
Labels: enhancement

#93 [merge / 81-feature-메인-피드-상세-페이지-코멘트-영역-퍼블리싱] ✨ feat: 메인 피드 게시물 상세 페이지 퍼블리싱 완료
  src/assets/images/course/course_comment_line_img.svg
  src/assets/images/course/course_user_profile_img.svg
  src/assets/images/course/location/location_accommodation_icon.svg
  src/assets/images/course/location/location_cafe_icon.svg
  src/assets/images/course/location/location_convenience_store_icon.svg
  src/assets/images/course/location/location_cultural_facility_icon.svg
  src/assets/images/course/location/location_parking_lot_icon.svg
  src/assets/images/course/location/location_restaurant_icon.svg
  src/assets/images/course/location/location_tourist_attraction_icon.svg
  src/assets/images/course/white_heart_filled_icon.svg
  src/assets/images/course/white_heart_not_filled_icon.svg
  src/assets/images/importImages.ts
  src/components/main/allCourse/AllCourseHeader.tsx
  src/components/main/allCourse/AllCourseSortToggle.tsx
  src/components/main/courseContent/CourseContentDoc.tsx
  src/components/main/courseContent/CourseLocationCardItem.tsx
  src/components/main/courseContent/commentArea/CommentList.tsx
  src/components/main/courseContent/commentArea/CommentListItem.tsx
  src/components/main/courseContent/commentArea/courseContentCommentArea.tsx
  src/components/main/courseContent/locationCardArea/CourseLocationCardItem.tsx
  src/components/main/courseContent/locationCardArea/CourseLocationCards.tsx
  src/components/main/utils/CourseSortToggle.tsx
  src/layouts/CourseContentLayout.tsx
  src/layouts/RootLayout.tsx
  src/pages/CourseContent.tsx
  src/types/mainfeed/props.d.ts
Labels: documentation

#98 [merge / 81-feature-메인-피드-상세-페이지-코멘트-영역-퍼블리싱]✨ feat: 메인 피드 상세페이지 location card 세로선 추가
  src/components/main/courseContent/locationCardArea/CourseLocationCards.tsx
  src/pages/createcourse/CourseEditor.module.css
Labels: documentation

#104 [merge / 81-feature-메인-피드-상세-페이지-코멘트-영역-퍼블리싱] ✨ feat: 메인 피드 상세페이지 API 연결
  package-lock.json
  package.json
  src/App.tsx
  src/api/postApi.ts
  src/components/main/MainAllCourse.tsx
  src/components/main/allCourse/AllCourseCardItem.tsx
  src/components/main/allCourse/AllCourseCards.tsx
  src/components/main/courseContent/CourseContentDoc.tsx
  src/main.tsx
  src/pages/CourseContent.tsx
  src/stores/mainFeedStore.ts
  src/types/mainfeed/props.d.ts
  src/types/post.d.ts
  src/utills/main/formatingDate.ts
Labels: documentation

#112 [merge / 107-feature-메인-피드-상세-페이지-api-연동 ]✨ feat: 상세 페이지 코스, 장소 정보 api 연결 완료
  src/components/main/allCourse/AllCourseCardItem.tsx
  src/components/main/allCourse/AllCourseCards.tsx
  src/components/main/courseContent/CourseContentDoc.tsx
  src/components/main/courseContent/locationCardArea/CourseLocationCardItem.tsx
  src/components/main/courseContent/locationCardArea/CourseLocationCards.tsx
  src/pages/CourseContent.tsx
  src/types/mainfeed/props.d.ts
  src/utills/main/fomatter.ts
  src/utills/main/formatingDate.ts
Labels: documentation

#113 [merge / 107-feature-메인-피드-상세-페이지-api-연동 ] ✨ feat: axiosInstance 토큰값 수정
  src/api/axios.ts
  src/api/commentApi.ts
  src/components/main/courseContent/CourseContentDoc.tsx
  src/components/main/courseContent/commentArea/CommentInputArea.tsx
  src/components/main/courseContent/commentArea/CommentList.tsx
  src/components/main/courseContent/commentArea/courseContentCommentArea.tsx
  src/utills/Auth/getTokenWithCloser.ts
  src/utills/main/fomatter.ts
Labels: documentation

#114 [merge / 107-feature-메인-피드-상세-페이지-api-연동 ]✨ feat: 상세 페이지 댓글 작성 & 노출 기능 구현 완료
  src/components/main/courseContent/commentArea/CommentInputArea.tsx
  src/pages/CourseContent.tsx
  src/utills/Auth/getTokenWithCloser.ts
Labels: documentation

#115 ✨ 카카오api를 사용하여 맵 화면 표시, 검색으로 맵 위치 변환 & 마커 생성, 리스트 클릭시 테두리 & 맵으로 화면 이동
  index.html
  package-lock.json
  package.json
  src/api/api.ts
  src/api/kakao/useKakaoLoader.ts
  src/components/Root/HeaderIcon.tsx
  src/components/Root/Nav.tsx
  src/components/createMyCourseMain/flow2/mapview/MapDisplay.tsx
  src/components/createMyCourseMain/flow2/mapview/SearchResultOfCreateMy.tsx
  src/components/createMyCourseMain/flow2/mapview/SearchResultOfCreateMyItems.tsx
  src/components/viewMycourse/ViewMyCourseHeader.tsx
  src/pages/Login.tsx
  src/pages/createcourse/MapView.tsx
  src/types/plaist.d.ts
Labels: enhancement

#118 로그인페이지 , 코스 생성 페이지 css 수정
  src/components/createMyCourseMain/flow2/mapview/MapDisplay.tsx
  src/pages/Login.tsx
Labels: enhancement

#122 로그인 페이지 로그인 보이기 버튼 수정
  src/assets/images/password_icon_password.png
  src/assets/images/password_icon_text.png
  src/pages/Login.tsx
Labels: enhancement

#127 123 feature 마이 코스 필터링
  src/api/postApi.ts
  src/api/userApi.ts
  src/components/createMyCourseMain/flow2/mapview/MapDisplay.tsx
  src/components/viewMycourse/ViewMyAllCourse.tsx
Labels: enhancement

#129 [merge / 107-feature-메인-피드-상세-페이지-api-연동]🐛 fix: 코드 병합 중 충돌 해결
  package-lock.json
  package.json
  src/App.tsx
  src/api/react-query/api.ts
  src/components/main/courseContent/commentArea/CommentInputArea.tsx
  src/components/main/courseContent/commentArea/courseContentCommentArea.tsx
  src/components/skeletonUI/Loader.tsx
  src/layouts/CourseContentLayout.tsx
  src/main.tsx
  src/pages/CourseContent.tsx
Labels: bug

#136 [merge / 107-feature-메인-피드-상세-페이지-api-연동] ✨ feat: 코스 상세 페이지 댓글 작성순, 최신순 정렬 기능 추가
  src/App.tsx
  src/api/userApi.ts
  src/components/main/courseContent/commentArea/CommentInputArea.tsx
  src/components/main/courseContent/commentArea/CommentList.tsx
  src/components/main/courseContent/commentArea/courseContentCommentArea.tsx
  src/components/main/utils/CourseSortToggle.tsx
  src/hooks/UseScrollTop.tsx
  src/pages/CourseContent.tsx
  src/stores/main/comment/useCommentStore.ts
  src/stores/main/comment/useSortStore.ts
  src/stores/useInfoStore.ts
  src/stores/userInfoStore.ts
  src/utills/main/fomatter.ts
Labels: documentation

#137 viewmycourse-검색-기능-logintsx-signuptsx-공통함수-utils로-통합
  src/api/api.ts
  src/components/utills/Validate.tsx
  src/components/viewMycourse/MyCourseCards.tsx
  src/components/viewMycourse/MyCourseSearch.tsx
  src/components/viewMycourse/ViewMyAllCourse.tsx
  src/pages/Login.tsx
  src/pages/Signup.tsx
Labels: enhancement

#146 [merge / 107-feature-메인-피드-상세-페이지-api-연동] Merge branch 'dev' into 107-feature-메인-피드-상세-페이지-api-연동
  src/api/react-query/courseApi.ts
  src/api/react-query/likeApi.ts
  src/assets/images/importImages.ts
  src/assets/images/like_not_filled_border_icon.svg
  src/assets/images/like_small_not_filled_icon.svg
  src/components/main/MainAllCourse.tsx
  src/components/main/allCourse/AllCourseCardItem.tsx
  src/components/main/courseContent/CourseContentDoc.tsx
  src/pages/CourseContent.tsx
  src/stores/main/like/useIsLikedStore.ts
  src/utills/main/fomatter.ts
  src/utills/main/likeButtonToggle.ts
Labels: documentation

#147 404페이지 추가, 맵 검색 리스트 fennel에 데이터추가 및 스타일 수정
  src/App.tsx
  src/components/createMyCourseMain/CreateMyCourseFlowButton.tsx
  src/components/createMyCourseMain/flow2/mapview/MapDisplay.tsx
  src/components/viewMycourse/MyCourseSearch.tsx
  src/pages/NotFound.tsx
  src/pages/createcourse/CreateMycourse.tsx
  src/pages/createcourse/MapView.tsx
  src/pages/createcourse/SelectTag.tsx
Labels: enhancement

#150 [merge / 107-feature-메인-피드-상세-페이지-api-연동]✨ feat: 좋아요 여부 상태 유지 기능 구현
  package-lock.json
  package.json
  src/api/postApi.ts
  src/assets/images/course/white_heart_not_filled_icon.svg
  src/components/main/allCourse/AllCourseCardItem.tsx
  src/components/main/courseContent/LikeButton.tsx
  src/pages/CourseContent.tsx
Labels: documentation

#151 ✨ feat: 댓글 입력창에 사용자 프로필 이미지 노출 기능 구현
  src/api/commentApi.ts
  src/components/main/courseContent/CourseContentDoc.tsx
  src/components/main/courseContent/LikeButton.tsx
  src/components/main/courseContent/commentArea/CommentInputArea.tsx
  src/components/main/courseContent/commentArea/CommentListItem.tsx
  src/pages/CourseContent.tsx
  src/types/mainfeed/commentProps.d.ts
Labels: documentation

#155 [merge / 152-feature-상세페이지-location-card-카테고리별-아이콘-적용] ✨ feat: 메인 페이지 best course API 연동 후 화면 노출 구현
  src/components/main/MainAllCourse.tsx
  src/components/main/MainBestCourse.tsx
  src/components/main/allCourse/AllCourseCardItem.tsx
  src/components/main/bestCourse/BestCourseCardItem.tsx
  src/components/main/bestCourse/BestCourseCards.tsx
  src/components/main/courseContent/commentArea/CommentInputArea.tsx
  src/pages/MainFeed.tsx
  src/stores/useInfoStore.ts
  src/utills/main/fomatter.ts
Labels: documentation

#156 ✨ 검색된-맵-리스트-선택한-데이터-지우기
  src/pages/createcourse/CreateMycourse.tsx
Labels: enhancement

#160 검색한-맵-리스트들-선택-리스트-중복-방지-처리, 리스트 선택 하지 않고 다음페이지 이동 방지
  src/components/createMyCourseMain/flow2/mapview/MapDisplay.tsx
  src/pages/createcourse/CreateMycourse.tsx
  src/pages/createcourse/MapView.tsx
Labels: enhancement

#163 [merge / 152-feature-상세페이지-location-card-카테고리별-아이콘-적용]✨ feat: 코스 상세 페이지 location card 장소별 아이콘 노출 기능 구현 완료
  src/assets/images/course/location/location_logo_icon.svg
  src/assets/images/importImages.ts
  src/components/main/bestCourse/BestCourseCardItem.tsx
  src/components/main/bestCourse/BestCourseCards.tsx
  src/components/main/courseContent/locationCardArea/CourseLocationCardItem.tsx
  src/utills/main/convertIcon.ts
  src/utills/main/fomatter.ts
Labels: documentation

#169 [merge/ 167-feature-메인-페이지-페이지네이션-구현]✨ feat: 메인 화면 페이지네이션 구현 완료
  src/App.tsx
  src/api/postApi.ts
  src/components/main/MainAllCourse.tsx
  src/components/main/utils/Pagenation.tsx
  src/layouts/MainLayout.tsx
  src/pages/main/CourseContent.tsx
  src/pages/main/MainFeed.tsx
Labels: documentation

#176 로그인 여부에 따른 알림 기능, 불필요한 패키지 제거
  package-lock.json
  package.json
  src/App.tsx
  src/api/api.ts
  src/components/createMyCourseMain/flow2/mapview/SearchResultOfCreateMyItems.tsx
Labels: enhancement

#178 alert창 커스텀 alert창으로 변경
  package-lock.json
  package.json
  src/App.tsx
  src/api/api.ts
  src/components/My/userInfo/UserInfoUpdate.tsx
  src/components/createMyCourseMain/flow2/mapview/MapDisplay.tsx
  src/components/main/courseContent/LikeButton.tsx
  src/components/main/courseContent/commentArea/CommentInputArea.tsx
  src/pages/CreateChannel.tsx
  src/pages/test/ChannelTest.tsx
Labels: enhancement

#184 [merge / refactor_root_layout_1]💄 update: 서비스 전체 레이아웃 재조정
  src/App.tsx
  src/Router.tsx
  src/components/My/MypageContents.tsx
  src/components/Root/Nav.tsx
  src/components/viewMycourse/MyCourseCards.tsx
  src/components/viewMycourse/MyCourseSearch.tsx
  src/components/viewMycourse/ViewMyAllCourse.tsx
  src/layouts/Blur.tsx
  src/layouts/LoginLayout.tsx
  src/layouts/MainLayout.tsx
  src/layouts/MyCourseLayout.tsx
  src/layouts/NoBlurLayout.tsx
  src/layouts/RootLayout.test.tsx
  src/layouts/RootLayout.tsx
  src/layouts/ViewMyCourseLayout.tsx
  src/layouts/utils/ScrollToTop.tsx
  src/pages/MyPage.tsx
  src/pages/createcourse/ViewMycourse.tsx
  src/pages/test/AuthTest.tsx
  src/pages/test/ChannelTest.tsx
  src/pages/test/SearchTest.tsx
  src/pages/test/UserTest.tsx
  src/types/mainfeed/props.d.ts
  src/utills/Auth/getTokenWithCloser.ts
  tailwind.config.js
Labels: documentation

#187 접근 권한 없는 페이지 로그인 페이지로 이동, 맵 재랜더링 수정
  src/components/My/MypageUserInfo.tsx
  src/components/createMyCourseMain/flow2/mapview/MapDisplay.tsx
  src/components/viewMycourse/ViewMyCourseHeader.tsx
  src/pages/MyPage.tsx
  src/pages/Notification.tsx
  src/pages/createcourse/SelectTag.tsx
  src/pages/createcourse/ViewMycourse.tsx
  src/types/plaist.d.ts
  tsconfig.json
Labels: enhancement

#189 [merge / 170-feature-메인-페이지-정렬최신순-인기순-토글]✨ feat: 메인 페이지 게시물 최신순 / 인기순으로 정렬 기능 구현 완료
  src/components/main/allCourse/AllCourseCardItem.tsx
  src/components/main/allCourse/AllCourseCards.tsx
  src/components/main/allCourse/AllCourseHeader.tsx
  src/components/main/bestCourse/BestCourseCardItem.tsx
  src/components/main/courseContent/commentArea/courseContentCommentArea.tsx
  src/components/main/courseContent/locationCardArea/CourseLocationCardItem.tsx
  src/components/main/utils/CourseAllCourseSortToggle.tsx
  src/components/main/utils/CourseCommentSortToggle.tsx
  src/stores/main/comment/useSortStore.ts
  src/utills/main/fomatter.ts
Labels: documentation

#196 마이코스 필터링, 검색 된 맵 리스트 선택 버튼 수정
  src/components/createMyCourseMain/flow2/mapview/MapDisplay.tsx
  src/components/createMyCourseMain/flow2/mapview/SearchResultOfCreateMyItems.tsx
  src/components/viewMycourse/ViewMyAllCourse.tsx
  src/hooks/useBackWithHistory.ts
  src/pages/createcourse/MapView.tsx
Labels: enhancement

#198 💄 fix: 게시판 상세페이지 css 조정
  index.html
  src/api/userApi.ts
  src/assets/images/plaist_pavicon.svg
  src/components/main/courseContent/commentArea/CommentInputArea.tsx
  src/components/main/courseContent/locationCardArea/CourseLocationCardItem.tsx
  src/layouts/MainLayout.tsx
  src/layouts/MyCourseLayout.tsx
  src/pages/main/CourseContent.tsx
  src/stores/login/useIsLoginStore.ts
  src/stores/useInfoStore.ts
  src/utills/main/likeButtonToggle.ts
Labels: documentation

#201 [merge / 200-bug-scrolltotop-일부-적용이-안되는-문제]🐛 fix: 다음 스텝으로 넘어갈때 최상단으로 안가지는 문제 수정
  src/pages/createcourse/CreateMycourse.tsx
Labels: bug

#202 [merge / 194-bug-상세-페이지-location-card-수정] 상세페이지 예외 처리, 파비콘 수정
  src/assets/images/plaist_pavicon.svg
  src/components/main/allCourse/AllCourseCardItem.tsx
  src/components/main/bestCourse/BestCourseCardItem.tsx
  src/components/main/courseContent/LikeButton.tsx
  src/components/main/courseContent/locationCardArea/CourseLocationCardItem.tsx
  src/pages/main/CourseContent.tsx
Labels: documentation

#211 [merge / 210-feature-상세페이지-작성자-프로필-이미지-노출-기능]✨ feat: 상세페이지 게시글 작성자 프로필 이미지 노출 기능 구현 완료
  src/Router.tsx
  src/api/api.ts
  src/api/react-query/likeApi.ts
  src/components/My/userInfo/UserInfoUpdate.tsx
  src/components/createMyCourseMain/flow2/mapview/MapDisplay.tsx
  src/components/main/courseContent/CourseContentDoc.tsx
  src/components/main/courseContent/commentArea/CommentInputArea.tsx
  src/components/main/courseContent/commentArea/CommentListItem.tsx
  src/pages/CreateChannel.tsx
Labels: documentation

#214 [merge / 212-bug-메인페이지-게시글-정렬-오류-수정] 🐛 fix: 메인페이지 게시물 정렬 오류 수정 및 코드 분리 완료
  src/components/main/MainAllCourse.tsx
  src/components/main/allCourse/AllCourseCards.tsx
  src/components/main/utils/Pagenation.tsx
  src/hooks/mainFeed/usePagenation.ts
  src/hooks/mainFeed/useSortedCourses.ts
  src/utills/main/fomatter.ts
Labels: bug

#219 리팩토링
  src/api/api.ts
  src/api/postApi.ts
  src/api/userApi.ts
  src/components/My/MyLike.tsx
  src/components/My/MypageCards/MypageCards.tsx
  src/components/My/MypageMyCourse.tsx
  src/components/My/MypageSearch.tsx
  src/components/category/Menu.tsx
  src/components/main/MainTitle.tsx
  src/components/viewMycourse/ViewMyAllCourse.tsx
  src/css/blur.css
  src/pages/createcourse/ViewMycourse.tsx
  src/stores/login/useIsLoginStore.ts
  src/types/plaist.d.ts
Labels: enhancement

#225 [merge / 224-feature-코스-생성-버튼에-hover효과-추가]✨ feat: 코스 생성버튼에 hover효과 추가
  src/assets/images/importImages.ts
  src/assets/images/start_to_create_button.svg
  src/components/viewMycourse/FixedCreateButton.tsx
  src/components/viewMycourse/ViewMyCourseHeader.tsx
Labels: documentation

#227 ✨ feat: plus_white_icon 추가
  src/assets/images/plus_white_icon.svg
Labels: documentation

#228 [merge / 221-bug-상세페이지-css-수정] 🐛 fix: 상세페이지 버그 수정
  src/Router.tsx
  src/components/main/courseContent/CourseBadge.tsx
  src/components/main/courseContent/CourseContentDoc.tsx
  src/components/main/courseContent/commentArea/CommentList.tsx
  src/components/main/courseContent/commentArea/courseContentCommentArea.tsx
  src/layouts/CourseContentLayout.tsx
  src/layouts/MainLayout.tsx
  src/pages/main/CourseContent.tsx
Labels: documentation

#234 [merge / 231-feature-게시물-생성-수정시-필요한-channel-list-만들기] ✨ feat: 게시물 생성 / 수정시 필요한 channel list 설계 완료
  src/pages/createcourse/CreateMycourse.tsx
  src/types/mycourse/channelList.d.ts
  src/utills/mycourse/findValueByKeyInSpot.ts
  src/utills/mycourse/setPostTitle.ts
Labels: documentation

#236 [merge / 224-feature-코스-생성-버튼에-hover효과-추가]🐛 fix: 코스 생성버튼이 의도치않은 방향으로 가는 문제 수정
  src/components/viewMycourse/FixedCreateButton.tsx
Labels: bug

#240 [merge / 235-refactor-상세페이지-css-디테일-수정]♻️ : 메인페이지, 상세페이지 CSS 일부 수정
  src/assets/images/basicImg.jpg
  src/assets/images/default.png
  src/components/My/MyLike.tsx
  src/components/main/MainAllCourse.tsx
  src/components/main/allCourse/AllCourseCardItem.tsx
  src/components/main/allCourse/AllCourseHeader.tsx
  src/components/main/courseContent/CourseContentDoc.tsx
  src/components/main/courseContent/LikeButton.tsx
  src/components/main/courseContent/locationCardArea/CourseLocationCardItem.tsx
  src/components/main/courseContent/locationCardArea/CourseLocationCards.tsx
  src/components/main/utils/ModifyButton.tsx
  src/pages/createcourse/CourseEditor.module.css
  src/pages/main/CourseContent.tsx
  src/stores/useLikesStore.ts
  src/stores/useMyCourseStore.ts
  src/utills/main/fomatter.ts
Labels: enhancement

#247 [merge / 235-refactor-상세페이지-css-디테일-수정] 🐛 fix: 코드 병합
  src/pages/OtherUserInfo.tsx
  src/stores/useLikesStore.ts
Labels: documentation

#252 [merge / 224 feature 코스 생성 버튼에 hover효과 추가]fix: 코스 생성 상단 mt수정
  src/assets/images/importImages.ts
  src/layouts/MyCourseLayout.tsx
  src/pages/createcourse/CreateMycourse.tsx
  src/pages/createcourse/ViewMycourse.tsx
Labels: bug

#259 ✨ 마이 코스 상세페이지에서 수정 여러번 하면 코스 삭제되는 오류 수정
  src/api/postMyCourse.ts
  src/components/viewMycourse/MyCourseCards.tsx
  src/components/viewMycourse/ViewMyAllCourse.tsx
  src/pages/Signup.tsx
  src/pages/main/CourseContent.tsx
Labels: enhancement

#261 [merge / 235-refactor-상세페이지-css-디테일-수정] ♻️ refactor: CourseContent.tsx onDlelteClicked 함수 로직 분리
  src/components/createMyCourseMain/CreateMycourseContent.tsx
  src/components/main/MainAllCourse.tsx
  src/pages/CreateChannel.tsx
  src/pages/PostEditor.tsx
  src/pages/main/CourseContent.tsx
  src/pages/main/handleDeletePost.ts
Labels: enhancement

#264 🐛 fix: 아이콘 크기 수정
  src/assets/images/course/location/location_restaurant_icon.svg
Labels: bug

#266 [merge / 235-refactor-상세페이지-css-디테일-수정]Merge branch 'dev' into 235-refactor-상세페이지-css-디테일-수정
  src/components/main/allCourse/AllCourseCards.tsx
  src/components/main/courseContent/commentArea/CommentInputArea.tsx
  src/components/main/courseContent/commentArea/CommentListItem.tsx
  src/layouts/MainLayout.tsx
  src/stores/useInfoStore.ts
Labels: documentation

#270 README.md 초안 작성
  README.md
Labels: documentation

#274 [merge / 273-bug-상세페이지-게시글-공백-입력-기능-수정]🐛 fix: 상세페이지 개행 오류 수정
  src/components/main/courseContent/CourseContentDoc.tsx
Labels: bug

#279 import 정리
  src/App.tsx
  src/Router.tsx
  src/api/api.ts
  src/api/axios.ts
  src/api/commentApi.ts
  src/api/postMyCourse.ts
  src/api/react-query/likeApi.ts
  src/api/userApi.ts
  src/assets/images/importImages.ts
  src/components/FooterNavLink.tsx
  src/components/HeaderNavLink.tsx
  src/components/My/MyComment.tsx
  src/components/My/MyComment/MyCommentCardItem.tsx
  src/components/My/MyLike.tsx
  src/components/My/MypageCards/MypageCardItem.tsx
  src/components/My/MypageCategoryTap.tsx
  src/components/My/MypageContents.tsx
  src/components/My/MypageMyCourse.tsx
  src/components/My/MypageProfile.tsx
  src/components/My/MypageUserInfo.tsx
  src/components/My/userInfo/UserInfoForm.tsx
  src/components/My/userInfo/UserInfoProfile.tsx
  src/components/My/userInfo/UserInfoUpdate.tsx
  src/components/Root/HeaderIcon.tsx
  src/components/Root/Nav.tsx
  src/components/category/Feed.tsx
  src/components/category/Menu.tsx
  src/components/main/MainAllCourse.tsx
  src/components/main/allCourse/AllCourseCardItem.tsx
  src/components/main/allCourse/AllCourseCards.tsx
  src/components/main/bestCourse/BestCourseCardItem.tsx
  src/components/main/bestCourse/BestCourseCards.tsx
  src/components/main/courseContent/CourseContentDoc.tsx
  src/components/main/courseContent/LikeButton.tsx
  src/components/main/courseContent/commentArea/CommentInputArea.tsx
  src/components/main/courseContent/commentArea/CommentList.tsx
  src/components/main/courseContent/commentArea/courseContentCommentArea.tsx
  src/components/main/courseContent/locationCardArea/CourseLocationCards.tsx
  src/components/notification/NotificationList.tsx
  src/components/utills/SearchBar.tsx
  src/components/utills/Validate.tsx
  src/components/viewMycourse/FixedCreateButton.tsx
  src/components/viewMycourse/ViewMyAllCourse.tsx
  src/hooks/mainFeed/useSortedCourses.ts
  src/layouts/RootLayout.tsx
  src/pages/Category.tsx
  src/pages/CreateChannel.tsx
  src/pages/Login.tsx
  src/pages/MyPage.tsx
  src/pages/NotFound.tsx
  src/pages/Notification.tsx
  src/pages/OtherUserInfo.tsx
  src/pages/PostEditor.tsx
  src/pages/Signup.tsx
  src/pages/createcourse/CreateMycourse.tsx
  src/pages/createcourse/ViewMycourse.tsx
  src/pages/main/CourseContent.tsx
  src/pages/main/MainFeed.tsx
  src/pages/main/handleDeletePost.ts
Labels: enhancement

#285 타입 에러 해결, ts 파일에서의 잘못된 store 문법 수정
  package.json
  src/Router.tsx
  src/components/category/Feed.tsx
  src/components/main/bestCourse/BestCourseCardItem.tsx
  src/components/main/courseContent/commentArea/CommentInputArea.tsx
  src/components/main/courseContent/commentArea/CommentList.tsx
  src/main.tsx
  src/pages/OtherUserInfo.tsx
  src/pages/createcourse/CreateMycourse.tsx
  src/stores/main/comment/useCommentStore.ts
  src/types/mainfeed/props.d.ts
  src/utills/Auth/setCookie.ts
  src/utills/main/fomatter.ts
  src/utills/mycourse/findValueByKeyInSpot.ts
  src/utills/mycourse/setPostTitle.ts
Labels: enhancement

#288 토큰 만료 모달 수정
  src/styles/category.css
  src/styles/feed.css
  src/styles/index.css
  src/utills/Auth/setCookie.ts
Labels: enhancement

#291 삭제된 css 파일 추가
  src/css/blur.css
  src/css/category.css
  src/css/font.css
  src/css/index.css
  src/css/tailwind.css
Labels: enhancement
